import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import Inter and assign the CSS variable
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // This sets --font-inter
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
